### ISSUE TITLE
[BUG] Wrong Encoding for midi length?

### ISSUE THREAD

**Issue by bxclib2** [spessasus/SpessaSynth#43] opened 2024-08-24 10:28 UTC
### Version
`spessasynth_lib`

### Description
 
I use the following step to encode midi:

```
const mid = new MIDIBuilder("Download", 480, 120);
let time = 0;

for (let i = 60; i < 67; i++) {
    mid.addNoteOn(0, 0, i, 127, time);
    time += 700;
}

mid.flush();

// Write the MIDI file to a blob and save it
const b = writeMIDIFile(mid);
const blob = new Blob([b.buffer], { type: "audio/mid" });
const url = URL.createObjectURL(blob);
const a = document.createElement("a");
a.href = url;
a.download = "C_major_scale.mid";
a.click();
```

Yep, i didn't append note off event. I wish the sound nature decay.

When i play this midi use the example, https://spessasus.github.io/SpessaSynth/, all things work good.

But I tried another two midi player, 

https://pianotify.com/import-midi-file
 
and 

https://cifkao.github.io/html-midi-player/

Both cannot work. Is this a designated behavior? I suspect it has a minor encoding issue of duration when no noteoff event is sent

### Reproduction steps
*Describe the steps to reproduce the behavior.*

### Expected behavior
*Provide a clear and concise description of what you expected to happen.*

### Screenshots
*If applicable, add screenshots to help explain your problem.*

### MIDI files and SoundFonts
*If the issue only persists with specific MIDIs or SoundFonts, add them here too. (preferably .zip)*
[C_major_scale (8).mid.zip](https://github.com/user-attachments/files/16736236/C_major_scale.8.mid.zip)

### Environment
*If the issue only persists on a smartphone, or only on a PC, or only on Chrome, etc. please specify.*

### Additional context
*Add any other context about the problem here that may be helpful.*

**Comment by spessasus** [comment] 2024-08-24 14:44
The file you provided is correctly formatted. However, it seems to me that those players expect a note off to determine a note's length but since there is none, they see it as no sound. Your should always send a note off at the end, but that's technically a bug on their end.

According to my testing:

Fluidsynth works fine and prints this: `fluidsynth: warning: End of the MIDI file reached, but not all notes have received a note off event! OFFing them now! Run with --verbose to spot pending voices.` 

Falcosoft MidiPlayer6 works fine

TiMidity++ works fine

and as you mentioned, spessa works fine. PS: the last note is the last event in the file after which all notes are stopped. That's why it's playing for a very short time.

Summing up, you should avoid sending note-ons without corresponding note-offs as some players always expect them. In your code, you can add another 700 ticks (for the last note) and then send the note off:
```js
import {MIDIBuilder, writeMIDIFile} from "spessasynth_lib";

const mid = new MIDIBuilder("Download", 480, 120);
let time = 0;

for (let i = 60; i < 67; i++) {
    mid.addNoteOn(time, 0, 0, i, 127);
    time += 700;
}
// send note off for all
for(let i = 60; i < 67; i++){
    mid.addNoteOff(time, 0, 0, i);
}

mid.flush();

// Write the MIDI file to a blob and save it
const b = writeMIDIFile(mid);
const blob = new Blob([b.buffer], { type: "audio/mid" });
const url = URL.createObjectURL(blob);
const a = document.createElement("a");
a.href = url;
a.download = "C_major_scale.mid";
a.click();
```
This code produces a file that correctly loads into html-midi-player.

Since this is not a bug, I'm closing this.

**Closed by spessasus** 2024-08-24 14:44 UTC
Labels: bug

**Comment by bxclib2** [comment] 2024-08-24 15:18
Okay I see thanks a lot!
