### ISSUE TITLE
[FEATURE REQUEST] Subtitle rendering support

### ISSUE THREAD

**Issue by TS53** [spessasus/SpessaSynth#69] opened 2024-10-29 14:46 UTC
**Is your feature request related to a problem? Please describe.**
I saw that loading lyrics is already supported, would it be possible to also support subtitle rendering maybe even ASS subtitles, by uploading a subtitle file?

**Is your feature related to the sound library or the app/website?**
The issue is only related to the app/website.

**Describe the solution you'd like**
- A possibility to upload a ASS subtitle together with a MIDI file
- By default render the ASS subtitle over all other GUI-elements like piano and settings with a library like [this](https://github.com/ThaUnknown/jassub) one.
- Be able to quit from the subtitles for example with ESC key, if a subtitle covers settings
- Be able to turn off subtitle rendering even if the subtitle was loaded

**Describe alternatives you've considered**
- stay with the lyrics-only method
- SRT subtitles: less styling support, simpler format

**Additional context**
- Rendering subtitles would be dependend on the bpm of the MIDI
- When a subtitle is given and no midi file, it could be "played" without music. But then a default bpm would be used that could be changed at best.
- If simple to implement, a subtitle voice waveform could get added whenever a word or a sentence in the subtitle is active (but low priority)

**Comment by spessasus** [comment] 2024-10-29 15:01
Subtitles? What for? What would be the use case for this?

**Comment by TS53** [comment] 2024-10-29 15:05
Karaoke support. Since the midi rendering works really good with Spessasynth, subtitle rendering would make it a perfect karaoke tool.

Yeah, I know that it's possible to embed the lyrics into the midi file, but it is less simple to read the lyrics at the expected time.
Thus, my request for the subtitle rendering.

**Comment by spessasus** [comment] 2024-10-29 15:08
Aren't .kar files used for this? According to my research, .ass is mostly used in videos.

**Comment by TS53** [comment] 2024-10-29 15:15
As far as I know, ASS subtitles are the way to go. They have specific [Karaoke tags](https://aegisub.org/docs/latest/ass_tags/), to easily allow making subtitles a perfect fit for karaoke.

It will also include all settings like color, font and position of the subtitle rendering. So, no new GUI settings are required for this.

**Comment by spessasus** [comment] 2024-10-29 20:03
> So, no new GUI settings are required for this.

 But a completely new system for displaying them is. If I'll ever implement this feature, it will simply allow importing these into the decoded text window.

**Comment by spessasus** [comment] 2024-10-29 20:08
And by the way, can you provide some example .ass Files?

**Comment by TS53** [comment] 2024-10-30 04:09
I will add some subtitles.

If I understand correctly, you mean that they would be rendered in the lyrics window? This would probably be a bit small, because I think currently there is ne resize possibility of this window.

**Comment by TS53** [comment] 2024-10-30 17:45
I have now created the files:
- a MIDI file for three choir voices
- an ASS subtitle with the three voices for the MIDI file
- a video as a test comparison to see the expected rendering

[Es geht eine dunkle Wolk herein.zip](https://github.com/user-attachments/files/17576893/Es.geht.eine.dunkle.Wolk.herein.zip)

**Comment by spessasus** [comment] 2024-12-07 17:50
I've taken a look at this ASS format and it indeed won't be rendered in the lyrics window, but in the main window over other GUI elements like you've suggested. I'll try to work on it soo.

**Comment by stgiga** [comment] 2024-12-08 02:28
I know that ASS subtitles have font support (https://www.reddit.com/r/linuxquestions/comments/prvdmr/comment/hegriik/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button), so you'd inevitably need a fallback font. Since Unicode is supported, you need a Pan-Unicode font to do this right. Mine in webfont form is only 3MiB (WOFF1, which is actually smaller and better than WOFF2 here), so it's reasonable.

**Comment by TS53** [comment] 2024-12-08 05:40
I think there are different ways of trying to solve the font problem:
1. try if some always available font with high unicode support can be accessed already from the library and use this as the fallback font.
2. The user can manually embed the font using [this](https://github.com/wyzdwdz/assfonts) tool in the ass file.
3. If 1. and 2. are not good enough: allow the user to upload fonts since the linked library "Supports all OpenType, TrueType and WOFF fonts, as well as embedded fonts". Either as two options ASS and subtitles or as one option with a ZIP file that has ASS and subtitles.
4. If 1. to 3. do not work use a direct download fallback font.

**Comment by stgiga** [comment] 2024-12-08 08:09
> I think there are different ways of trying to solve the font problem:
> 
>     1. try if some always available font with high unicode support can be accessed already from the library and use this as the fallback font, without downloading one.
> 
>     2. The user can manually embed the font using [this](https://github.com/wyzdwdz/assfonts) tool in the ass file.
> 
>     3. If 1. and 2. are not good enough: allow the user to upload fonts since the linked library "Supports all OpenType, TrueType and WOFF fonts, as well as embedded fonts". Either as two options ASS and subtitles or as one option with a ZIP file that has ASS and subtitles.
> 
>     4. If 1. to 3. do not work use a direct download fallback font.

Well luckily, I offer UnifontEX in ALL webfont formats, and as a CSS that loads them.

**Comment by spessasus** [comment] 2024-12-08 14:33
I think that the font will simply stay the same as the rest of the program (I.E. `system-ui`) to stay consistent.

**Comment by TS53** [comment] 2024-12-08 19:37
Font "system-ui" seems to be a very good choice, but for me it sounds like a "local font". I have not tested it, but it seems that such fonts are difficult to load with the library. But maybe (and hopefully) this is complete wrong.

I will add an ASS with embedded font soon.

**Comment by spessasus** [comment] 2024-12-08 19:52
> Font "system-ui" seems to be a very good choice, but for me it sounds like a "local font". I have not tested it, but it seems that such fonts are difficult to load with the library. But maybe (and hopefully) this is completely wrong.
> 
> I will add an ASS with embedded font soon.

System ui is the font that your OS uses. And I don't plan on using any libraries, I'm making my own simple parser :-)

**Comment by TS53** [comment] 2024-12-08 20:33
If you mean to create your own parser and renderer, "system-ui" probably works. But I assume it will be a difficult task to build your own. Not just the karaoke tags, but also the positioning of the subtitles are difficult to achieve. If two subtitles appear at same position at same time, it is the task of the renderer to reposition them in such way that they don't overlap.


It seems the tool gives a working subtitle with embedded font. I see no difference to the other one:
`assfonts.exe -i input_subtitle.ass -o "path\to\output\folder" -f "path\to\folder\of\font"`
[DunkleWolkEmbed.zip](https://github.com/user-attachments/files/18053882/DunkleWolkEmbed.zip)

**Comment by stgiga** [comment] 2024-12-09 00:51
I think that the problem is also with lyrics beyond just subtitles. System fonts may not cut it when dealing with CJK, and not to mention other scripts. 3MiB is literally nothing.

**Comment by spessasus** [comment] 2024-12-11 22:32
Hi.

You can follow the development on the `ass-support` branch.

**Comment by spessasus** [comment] 2024-12-23 09:30
Hi, @TS53 

A semi-working draft is currently implemented in the `ass-support` branch. It doesn't have anti-overlapping just yet, but let me know what you think about it.

**Comment by TS53** [comment] 2024-12-23 12:44
Really amazing work, congratulations and thanks for implementing this, it's impressive!
I think, the overlapping looks quite okay and not problematic, at least in the given subtitle.

Only a few things are not aligned with the test video:
- all subtitles start (one note?) too late. At least it can be seen easily with the lower one. We can also see, that the lower subtitle starts in white color, but it should start in red color `Dialogue: 0,0:00:00.00,0:00:09.50,B,GesangstimmeDrei,0,0,0,,{\k50}Es {\k100}geht`.
The other two voices have an empty \k at the start, which is only to make the first word start in white color and delay the first start, for example:
`Dialogue: 0,0:00:02.00,0:00:15.00,T,GesangstimmeEins,0,0,0,,{\k100}{\k50}Es {\k100}geht`.
For the first subtitle, this does not work, I think, because Spessasynth starts music playing at 00:00 always, there is no falling notes at the beginning for like 2 seconds. If it would be like this, we could already display a subtitle before and make it white also. But because of this, I let the test subtitle start at 00:00 and thus it should have red color.
- The \K tag seems to work but it seems to sometimes block the \k tag before (the word before). In the test video at second 7.5 we can see at the lower subtitle the word "herein", which is put together using two tags `{\k50}her{\K150}ein,`. Here, the first tag should already be red before the second one starts. But when the \K tag appears, it will block the previous word until the \K tag starts. Then, both start at the same time. The expected result, can be seen in the video.
- when the subtitle is loaded at start, the lyrics windows does not close automatically. It is a bit hard to close it manually after the subtitle is loaded.

When I see more issues, I will add them here.

**Comment by spessasus** [comment] 2024-12-23 12:54
Hi,
First of all, thanks for the kind words! :)

About the first issue, i've been trying to figure that one out for a bit now.
`{\k50}Es` looks like `Es` should get highlighted 0.5 seconds after the start, not instantly. So why does it get highlighted instantly in other players? I'm really not quite sure and I'm curious on your thoughts about this.

**Comment by TS53** [comment] 2024-12-23 12:58
I think it means "the text after this [k tag](https://aegisub.org/docs/latest/ass_tags/) should be displayed using the k styling for 50ms"

Thus, an empty k tag at the start technically is rendered already at 00:00 but since it is empty, we don't see it.
I think, this is the only way in ASS to show the tags before they immediately get red.

**Comment by spessasus** [comment] 2024-12-23 13:26
Alright, I see! I've fixed the timings, should work properly now.

Also, about:
> when the subtitle is loaded at start, the lyrics windows does not close automatically. It is a bit hard to close it manually after the subtitle is loaded.

You can use the keybind (`T`) or press `Esc` to hide the subtitles. Also you can click through them.

**Comment by TS53** [comment] 2024-12-23 17:28
I think embedded fonts are not working and replaced using a default font. Is it expected to work already?
`Request for font "name of the font" blocked at visibility level 2 (requires 3)`

**Comment by spessasus** [comment] 2024-12-23 17:37
No, the embedded fonts are not implemented. BTW, I've added anti overlapping and made the lyrics menu automatically close. Feel free to test it! The animated `\K` artifacts should also be fixed now.

**Comment by TS53** [comment] 2024-12-23 17:38
Thanks, I will test it!

I found the spec for embedded fonts:

```
Appendix B: embedded font/picture encoding

SSA’s font and picture file embeddeding is a form of UUEncoding.

It takes a binary file, three bytes at a time, and converts the 24bits of those bytes into four 6-bit numbers. 33 is added to each of these four numbers, and the corresponding ascii character for each number is written into the script file.

The offset of 33 means that lower-case characters cannot appear in the encoded output, and this is why the “filename” lines are always lower case.

Each line of an encoded file is 80 characters long, except the last one, which may be shorter.

If the length of the file being encoded is not an exact multiple of 3, then for odd-number filelengths, the last byte is multiplied by hexadecimal 100, and the most significant 12 bits are converted to two characters as above. For even-number filelengths, the last two bytes are multiplied by hexadecimal 10000, and the most significant 18 bits are converted to three characters as above. 

There is no terminating code for the embedded files. If a new [section] starts in the script, or if another filename line is found, or the end of the script file is reached then the file is considered complete.
```

**Comment by TS53** [comment] 2024-12-23 17:42
Really good work!! Just one thing: When the line originally was lower and the overlapped get upper, when I now press <- to go back, the first line is now upper, where we expect it to be lower again. It's not so important but a little bit undeterministic.

**Comment by spessasus** [comment] 2024-12-23 17:53
Alright, should be fixed now.
And artifacts too, i promise!!!!

**Comment by TS53** [comment] 2024-12-23 17:56
Yes, I think it is flawless now!! Nice, very good work!

**Comment by spessasus** [comment] 2024-12-23 18:10
I've created a PR. Is it good enough to release or should I add something else?

**Comment by TS53** [comment] 2024-12-23 18:12
It's good enough, but it would be perfect with embedded font supported.
But I think, for now it's enough. Thank you!

**Comment by spessasus** [comment] 2024-12-23 18:14
> It's good enough, but it would be perfect with embedded font supported. But I think, for now it's enough. Thank you!

Alright, can you upload DunkleWolk with a custom font? Because if it's arial I can't tell if it's the embedded one or a system one.

**Comment by TS53** [comment] 2024-12-23 18:16
If have already done it a few minutes ago, [here](https://github.com/spessasus/SpessaSynth/issues/69#issuecomment-2560081335).

**Comment by spessasus** [comment] 2024-12-23 18:23
Sorry, I didn't notice. I'll work on it!

**Comment by spessasus** [comment] 2024-12-23 19:21
Alright, it seems to work for me. (Playwright) is it goood to you? @TS53

**Comment by TS53** [comment] 2024-12-23 19:34
Playwright seems to work perfect, but others don't. According to the debug output it seems possible that the problem comes from `assfonts.exe` converter tool.
So I think you can merge the PR now!
Thank you very much for implementing this!

**Comment by TS53** [comment] 2024-12-23 19:35
Hm, wait.

**Comment by TS53** [comment] 2024-12-23 19:39
It seems, most subtitles actually work. What I faced was just the problem, that once a bad one is loaded no subtitle works again until I fresh the page. So you can merge it now!

**Comment by spessasus** [comment] 2024-12-23 19:43
Alright, merged!

**Closed** 2024-12-23 19:42 UTC
Labels: enhancement
